# Generated by Django 5.2.17 on 2026-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='hr_contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='interview',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='interview',
            name='hr_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
