# Generated by Django 5.2.17 on 2026-10-03 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_interview_hr_contact_number_interview_hr_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
