# Generated by Django 5.2.17 on 2026-10-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_user_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=128)),
                ('verification_token_hash', models.CharField(max_length=64)),
                ('verification_expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('awaiting_verification', 'Awaiting email verification'), ('awaiting_approval', 'Awaiting admin approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='awaiting_verification', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting_verification', 'awaiting_approval'])), fields=('username',), name='unique_active_registration_username'), models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting_verification', 'awaiting_approval'])), fields=('email',), name='unique_active_registration_email')],
            },
        ),
    ]
