# Generated by Django 5.2.17 on 2026-10-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_studentregistrationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistrationrequest',
            name='status',
            field=models.CharField(choices=[('awaiting_verification', 'Awaiting email verification'), ('awaiting_approval', 'Awaiting admin approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='awaiting_verification', max_length=24),
        ),
    ]
