# Generated by Django 5.2.17 on 2026-10-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_registration_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='job_posting_url',
            field=models.URLField(blank=True),
        ),
    ]
