# Generated by Django 5.2.17 on 2026-10-05 17:55

from django.db import migrations, models


COURSES = [
    (
        "Python",
        "Build programming foundations and learn to write clear, useful Python.",
        "Set up Python and learn basic syntax\nWork with strings, numbers, collections and control flow\nWrite functions and organize code into modules\nHandle errors, files and common data formats\nBuild a small command-line project and test it",
        "What is the difference between a list and a tuple?\nHow do Python dictionaries handle keys?\nWhat is the purpose of a generator?\nExplain mutable and immutable objects in Python.\nHow would you handle exceptions when reading a file?",
        1,
    ),
    (
        "SQL (PostgreSQL)",
        "Query relational data and use PostgreSQL features to work with real datasets.",
        "Understand tables, rows, keys and relationships\nWrite SELECT queries with filters, sorting and joins\nAggregate data with GROUP BY and window functions\nUse indexes, constraints and transactions\nModel and analyze a sample relational dataset",
        "What is the difference between INNER JOIN and LEFT JOIN?\nWhen would you use a window function?\nWhat is a database index and what are its trade-offs?\nHow do NULL values affect comparisons and aggregates?\nWhat does ACID mean for a database transaction?",
        2,
    ),
    (
        "AWS",
        "Learn core AWS services and the fundamentals of deploying cloud workloads.",
        "Explore regions, availability zones and IAM\nStore files with S3 and serve static content\nRun compute workloads with EC2 and Lambda\nConnect services with VPC networking and security groups\nDeploy a small, monitored cloud application",
        "What is the difference between an IAM role and an IAM user?\nHow does S3 provide durable object storage?\nWhen would you choose Lambda over EC2?\nWhat is a VPC security group?\nHow would you make a service highly available across zones?",
        3,
    ),
    (
        "GCP",
        "Get familiar with Google Cloud services for compute, data and application delivery.",
        "Understand projects, billing and IAM\nStore objects in Cloud Storage\nRun workloads with Compute Engine and Cloud Run\nQuery analytics data with BigQuery\nDeploy and monitor a small cloud service",
        "What is the purpose of a GCP project?\nWhen would you use Cloud Run instead of Compute Engine?\nHow does BigQuery differ from a traditional database?\nHow should service accounts be used securely?\nWhat approaches can reduce cloud storage and compute costs?",
        4,
    ),
    (
        "PySpark",
        "Process large datasets with distributed data transformations using PySpark.",
        "Create a Spark session and load structured data\nTransform DataFrames with select, filter and withColumn\nJoin and aggregate data across partitions\nHandle schemas, nulls and common data formats\nBuild a reusable batch data-processing pipeline",
        "What is lazy evaluation in Spark?\nWhat is the difference between a transformation and an action?\nHow can data skew affect a join?\nWhen should you use a broadcast join?\nHow do repartition and coalesce differ?",
        5,
    ),
    (
        "Databricks",
        "Use the Databricks platform and Delta Lake to develop collaborative data workflows.",
        "Navigate workspaces, notebooks and compute\nRead and write data with Spark and Delta tables\nUse Delta Lake features for reliable data changes\nBuild and schedule a multi-step data workflow\nApply access controls and monitor a job run",
        "What benefits do Delta tables provide over plain Parquet files?\nHow does time travel work in Delta Lake?\nWhat is a Databricks job used for?\nHow would you manage secrets for a notebook workflow?\nHow can you investigate a slow Spark job in Databricks?",
        6,
    ),
    (
        "Django",
        "Build secure web applications using Django models, views, templates and forms.",
        "Create a project and define URL routes\nModel data and apply database migrations\nBuild views and render templates\nValidate user input with forms\nAdd authentication, permissions and automated tests",
        "What is Django's MTV architecture?\nHow do migrations keep a database schema in sync with models?\nWhat is the difference between select_related and prefetch_related?\nHow does Django protect forms from CSRF attacks?\nHow would you restrict a view to the owner of a record?",
        7,
    ),
]


def seed_courses(apps, schema_editor):
    LearningCourse = apps.get_model("tracker", "LearningCourse")
    LearningCourse.objects.using(schema_editor.connection.alias).bulk_create([
        LearningCourse(
            name=name,
            summary=summary,
            roadmap=roadmap,
            interview_questions=questions,
            sort_order=sort_order,
        )
        for name, summary, roadmap, questions, sort_order in COURSES
    ])


def unseed_courses(apps, schema_editor):
    LearningCourse = apps.get_model("tracker", "LearningCourse")
    LearningCourse.objects.using(schema_editor.connection.alias).filter(
        name__in=[course[0] for course in COURSES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_interview_job_posting_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('summary', models.TextField()),
                ('roadmap', models.TextField(help_text='Add one roadmap step per line.')),
                ('interview_questions', models.TextField(help_text='Add one sample interview question per line.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(seed_courses, unseed_courses),
    ]
