# Generated by Django 5.2.17 on 2026-10-05 18:22

from django.db import migrations, models


COURSE_DETAILS = {
    "Python": (
        "Beginner",
        "6 weeks",
        "Basic computer skills; no prior programming required.",
        "Write readable Python scripts and functions\nUse lists, dictionaries, sets and tuples appropriately\nRead and write files, handle exceptions and use packages\nTest code and build a small command-line application",
        "Python 3\nVS Code\nGit",
    ),
    "SQL (PostgreSQL)": (
        "Beginner to intermediate",
        "5 weeks",
        "Basic spreadsheet or data literacy is helpful.",
        "Write clear queries against relational data\nCombine and aggregate data with joins and window functions\nDesign tables with appropriate keys and constraints\nExplain basic query plans and index trade-offs",
        "PostgreSQL\npgAdmin or psql\nSample relational datasets",
    ),
    "AWS": (
        "Beginner",
        "6 weeks",
        "Basic networking concepts and command-line familiarity.",
        "Explain core cloud and IAM concepts\nStore and serve files with S3\nChoose suitable compute with EC2 and Lambda\nDeploy a small service with least-privilege access and monitoring",
        "AWS Management Console\nAWS CLI\nIAM, S3, EC2, Lambda and CloudWatch",
    ),
    "GCP": (
        "Beginner",
        "5 weeks",
        "Basic networking concepts and command-line familiarity.",
        "Organize resources with projects and IAM\nChoose a suitable compute service for a workload\nLoad and analyze data with BigQuery\nDeploy and monitor a small Google Cloud service",
        "Google Cloud Console\nCloud Shell\ngcloud CLI\nCloud Storage, Cloud Run and BigQuery",
    ),
    "PySpark": (
        "Intermediate",
        "5 weeks",
        "Comfort with Python and basic SQL is recommended.",
        "Transform structured data with Spark DataFrames\nUse joins, grouping and aggregations effectively\nReason about partitions, shuffles and skew\nBuild a repeatable batch processing pipeline",
        "Python\nPySpark\nApache Spark\nJupyter or Databricks Community Edition",
    ),
    "Databricks": (
        "Intermediate",
        "4 weeks",
        "Basic SQL and familiarity with Spark or data processing.",
        "Develop collaborative notebook workflows\nCreate and query Delta tables\nApply reliable data change and recovery patterns\nSchedule and troubleshoot data jobs",
        "Databricks workspace\nApache Spark\nDelta Lake\nSQL",
    ),
    "Django": (
        "Intermediate",
        "5 weeks",
        "Basic Python, HTML and CSS are recommended.",
        "Build a web app with models, views, templates and URLs\nValidate input with forms and protect views with permissions\nUse migrations and ORM query patterns effectively\nTest and deploy a small secure web application",
        "Python\nDjango\nSQLite or PostgreSQL\nHTML and CSS",
    ),
}


def populate_course_details(apps, schema_editor):
    LearningCourse = apps.get_model("tracker", "LearningCourse")
    manager = LearningCourse.objects.using(schema_editor.connection.alias)
    for name, values in COURSE_DETAILS.items():
        level, duration, prerequisites, outcomes, tools = values
        manager.filter(name=name).update(
            level=level,
            duration=duration,
            prerequisites=prerequisites,
            learning_outcomes=outcomes,
            tools=tools,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_learningcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcourse',
            name='duration',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='learningcourse',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Add one learning outcome per line.'),
        ),
        migrations.AddField(
            model_name='learningcourse',
            name='level',
            field=models.CharField(default='Beginner', max_length=40),
        ),
        migrations.AddField(
            model_name='learningcourse',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningcourse',
            name='tools',
            field=models.TextField(blank=True, help_text='Add one tool or platform per line.'),
        ),
        migrations.RunPython(populate_course_details, migrations.RunPython.noop),
    ]
